### GENERAL SETTINGS ###

# Site settings
title: Alex Allman
description: "Budding Games developer with fresh eyes on the topic."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/" #important: start with /
url: "https://Xelarse.github.io/"

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#708090" #"#F70031"
  primary_rgb: "112,128,144" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: false
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: linkedin
    url: https://www.linkedin.com/in/alexander-allman-953aa5176/

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Ross-On-Wye,
    - United Kingdom.
email: alexallmandev@gmail.com



### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Alexander Allman
    position: Games technology grad and full time software engineer
    text: A major fan of games whos taking the plunge into developing them and the switch in mindset that it requires.
    img: Profile_1.jpg
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/alexander-allman-953aa5176/

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "A major fan of games whos taking the plunge into developing them and the switch in mindset that it requires."
